server:
  port: 80

app:
  domain: 34.71.229.203

spring:
  datasource:
    url: ${sm@db-url}
    username: ${sm@db-username}
    password: ${sm@db-password}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  docker:
    compose:
      lifecycle-management: start-only
  data:
    redis:
      host: ${sm@redis-host}
      port: ${sm@redis-port}
      username: default
      password: ${sm@redis-password}
      ssl:
        enabled: true
jwt:
  secret: ${sm@jwt-secret}